plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sayanthrock.colorosthemes.lsposed'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sayanthrock.colorosthemes.lsposed'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '0.3.3'
        buildConfigField 'boolean', 'DEBUG_SAFE_HOOKS', 'false'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
